project_id = "rtokrinjgtlawspafznl"

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.generate-payslip]
verify_jwt = true

[functions.get-public-invoice]
verify_jwt = false
